name: flashcard_app
description: "A flashcard learning app using Firebase Firestore and Authentication."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  intl: ^0.19.0

  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Services
  google_sign_in: ^6.2.1
  http: ^1.2.1
  
  # Tiện ích
  flutter_dotenv: ^5.1.1

  # Giao diện
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # SỬA: Đã sửa lỗi thụt lề
  assets:
    - .env
    - assets/images/