name: flashcard_app
description: "A flashcard learning app using Firebase Firestore and Authentication."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Services
  google_sign_in: ^6.2.1
  http: ^1.2.1
  
  # Notifications & Timezone
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  
  # Utils
  flutter_dotenv: ^5.1.1
  intl: ^0.19.0

  # Giao diện
  cupertino_icons: ^1.0.8
  # MỚI: Thư viện biểu đồ
  fl_chart: ^0.68.0
  flutter_sparkline: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/